//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/Input/PlayerInputActionMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActionMaps: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActionMaps()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActionMaps"",
    ""maps"": [
        {
            ""name"": ""Game_Movement"",
            ""id"": ""284a8389-736a-46da-8dfe-8d046864f792"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""205cabb5-ad49-4534-8a0f-bb28b4929fe9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e6ca787f-73d4-47fb-ad85-b38ad5766e68"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d4eab746-4b24-42dc-b6f6-43ae1fa055a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FireLeftPortal"",
                    ""type"": ""Button"",
                    ""id"": ""cc20e54c-7e53-4d06-ba62-c7de5aefc41f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireRightPortal"",
                    ""type"": ""Button"",
                    ""id"": ""7deaef38-0ca2-42c1-ac1f-cc903f7e19d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause Game"",
                    ""type"": ""Button"",
                    ""id"": ""711c3a0f-087a-46e3-9b5a-68e702dcfb7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""d9502425-f716-4004-a79e-279f6dfcee58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""00ca640b-d935-4593-8157-c05846ea39b3"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e2062cb9-1b15-46a2-838c-2f8d72a0bdd9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8180e8bd-4097-4f4e-ab88-4523101a6ce9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""320bffee-a40b-4347-ac70-c210eb8bc73a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1c5327b5-f71c-4f60-99c7-4e737386f1d1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2581a9b-1d11-4566-b27d-b92aff5fabbc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2e46982e-44cc-431b-9f0b-c11910bf467a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcfe95b8-67b9-4526-84b5-5d0bc98d6400"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""77bff152-3580-4b21-b6de-dcd0c7e41164"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1635d3fe-58b6-4ba9-a4e2-f4b964f6b5c8"",
                    ""path"": ""<XRController>/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ea4d645-4504-4529-b061-ab81934c3752"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8e490b-c610-4785-884f-f04217b23ca4"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse;Touch"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e5f5442-8668-4b27-a940-df99bad7e831"",
                    ""path"": ""<Joystick>/{Hatswitch}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143bb1cd-cc10-4eca-a2f0-a3664166fe91"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""FireLeftPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05f6913d-c316-48b2-a6bb-e225f14c7960"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""FireLeftPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""886e731e-7071-4ae4-95c0-e61739dad6fd"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""FireLeftPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee3d0cd2-254e-47a7-a8cb-bc94d9658c54"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""FireLeftPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8255d333-5683-4943-a58a-ccb207ff1dce"",
                    ""path"": ""<XRController>/{PrimaryAction}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""FireLeftPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22291349-000d-4c3d-88cc-8dd36d4b0698"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bca84ccd-7309-4675-8a12-449ca5baadd6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abaaef22-6eed-45fb-884d-c7984e4f9580"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FireRightPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb10321f-2f05-4028-9d57-5b82996b45e5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FireRightPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e23fb0c0-8e11-449e-a864-8e176135a8e9"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""FireRightPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34d8d73d-79d5-4391-878c-5cb0657dd992"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""FireRightPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb13f4b9-dcd6-43e2-b5cd-4a453829df2f"",
                    ""path"": ""<XRController>/{PrimaryAction}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""FireRightPortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7263f097-ab3a-4e0b-b17f-4f8c0bd94358"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""745577ae-e636-4824-9a4e-98bfcb576142"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e889db71-e22b-4069-8aca-7025c1d1697f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a8c3dd3-bd2c-4587-8bff-d232fb9eeaea"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Game_PauseMenu"",
            ""id"": ""eeef3626-47c8-4612-9b41-63ad8d35f3f7"",
            ""actions"": [
                {
                    ""name"": ""Pause_MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""268267d7-cdf5-48e4-8f3a-ec2320db235a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause_MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""48b9e495-22a1-4bce-a1b4-29291afc94b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause_Select"",
                    ""type"": ""Button"",
                    ""id"": ""c9845729-106d-4961-89a4-cabcaa3c87a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause_Return"",
                    ""type"": ""Button"",
                    ""id"": ""2b363476-f149-4fc5-abf0-b0c681e157c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a94d7a34-ea32-4915-91da-c0f3d39d9cc2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71963b2b-e147-400f-8e30-598cbc03093c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a151e21-74e6-4df8-a988-194bfd46ddf7"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""409e8793-80a9-4605-84a1-65128a2de78c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bba200e8-125b-4972-9e52-1cddbb40dc59"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a5444aa-9448-4bee-be11-2bdd82307c72"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bc3c79c-9add-45c4-aae1-b44187b419eb"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""963ebb65-8438-4454-9d44-d08f1f09e9e6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""325751fb-bf9f-4331-ba6d-54a8726c166e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3bcb76f-10f8-4790-926b-7409e9c986bd"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause_Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""7dc4f22f-30e0-4485-b009-cbeefa900db5"",
            ""actions"": [
                {
                    ""name"": ""Start_Select_Up"",
                    ""type"": ""Button"",
                    ""id"": ""1baae8dc-4fed-4b88-ab89-38fa5047b49a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start_Select_Down"",
                    ""type"": ""Button"",
                    ""id"": ""aadc1d0f-1d9b-4b18-b9a5-87ddddb225de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start_Select"",
                    ""type"": ""Button"",
                    ""id"": ""c2532e3e-fe01-44df-8572-d84837199208"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a0e1955a-f321-443b-807a-094aefb8b8d5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ff2b253-3897-4516-aae2-8355a2adffb5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""360ec138-077b-4251-b19c-557dbc840565"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92448c1a-f489-40a0-9475-b16b9ec3fbae"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df46da1c-d282-4ee2-83ee-5b69d85523ec"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""540be18f-a6a2-4eeb-abe3-aa32f5cee989"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu_Settings"",
            ""id"": ""2b2599db-f953-40f6-b15e-ad113485f204"",
            ""actions"": [
                {
                    ""name"": ""Settings_Select_Up"",
                    ""type"": ""Button"",
                    ""id"": ""30622591-acdb-4757-b8d1-d654a15f1bda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings_Select_Down"",
                    ""type"": ""Button"",
                    ""id"": ""8e3d23e4-2799-4146-83cc-dfc8f467c91d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings_Select"",
                    ""type"": ""Button"",
                    ""id"": ""9970553e-7bde-4a29-b25c-f30c0df66b40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fb755c89-04d6-47e1-8c39-3f90392b7a34"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settings_Select_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4deb528b-ea24-4220-9379-5309f7efdae9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settings_Select_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b7bc75f-ea9d-4263-af72-eb659ef5f8fa"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settings_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu_SaveSelect"",
            ""id"": ""a39acd36-2872-4cda-be6a-1ed47d7033d6"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""609290aa-a1e5-4a6b-a894-bd893fbf2efb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a34ddec3-2d16-4039-a0ac-7fba5157e251"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game_Movement
        m_Game_Movement = asset.FindActionMap("Game_Movement", throwIfNotFound: true);
        m_Game_Movement_Move = m_Game_Movement.FindAction("Move", throwIfNotFound: true);
        m_Game_Movement_Look = m_Game_Movement.FindAction("Look", throwIfNotFound: true);
        m_Game_Movement_Jump = m_Game_Movement.FindAction("Jump", throwIfNotFound: true);
        m_Game_Movement_FireLeftPortal = m_Game_Movement.FindAction("FireLeftPortal", throwIfNotFound: true);
        m_Game_Movement_FireRightPortal = m_Game_Movement.FindAction("FireRightPortal", throwIfNotFound: true);
        m_Game_Movement_PauseGame = m_Game_Movement.FindAction("Pause Game", throwIfNotFound: true);
        m_Game_Movement_Interact = m_Game_Movement.FindAction("Interact", throwIfNotFound: true);
        // Game_PauseMenu
        m_Game_PauseMenu = asset.FindActionMap("Game_PauseMenu", throwIfNotFound: true);
        m_Game_PauseMenu_Pause_MoveUp = m_Game_PauseMenu.FindAction("Pause_MoveUp", throwIfNotFound: true);
        m_Game_PauseMenu_Pause_MoveDown = m_Game_PauseMenu.FindAction("Pause_MoveDown", throwIfNotFound: true);
        m_Game_PauseMenu_Pause_Select = m_Game_PauseMenu.FindAction("Pause_Select", throwIfNotFound: true);
        m_Game_PauseMenu_Pause_Return = m_Game_PauseMenu.FindAction("Pause_Return", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_Start_Select_Up = m_MainMenu.FindAction("Start_Select_Up", throwIfNotFound: true);
        m_MainMenu_Start_Select_Down = m_MainMenu.FindAction("Start_Select_Down", throwIfNotFound: true);
        m_MainMenu_Start_Select = m_MainMenu.FindAction("Start_Select", throwIfNotFound: true);
        // MainMenu_Settings
        m_MainMenu_Settings = asset.FindActionMap("MainMenu_Settings", throwIfNotFound: true);
        m_MainMenu_Settings_Settings_Select_Up = m_MainMenu_Settings.FindAction("Settings_Select_Up", throwIfNotFound: true);
        m_MainMenu_Settings_Settings_Select_Down = m_MainMenu_Settings.FindAction("Settings_Select_Down", throwIfNotFound: true);
        m_MainMenu_Settings_Settings_Select = m_MainMenu_Settings.FindAction("Settings_Select", throwIfNotFound: true);
        // MainMenu_SaveSelect
        m_MainMenu_SaveSelect = asset.FindActionMap("MainMenu_SaveSelect", throwIfNotFound: true);
        m_MainMenu_SaveSelect_Newaction = m_MainMenu_SaveSelect.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game_Movement
    private readonly InputActionMap m_Game_Movement;
    private List<IGame_MovementActions> m_Game_MovementActionsCallbackInterfaces = new List<IGame_MovementActions>();
    private readonly InputAction m_Game_Movement_Move;
    private readonly InputAction m_Game_Movement_Look;
    private readonly InputAction m_Game_Movement_Jump;
    private readonly InputAction m_Game_Movement_FireLeftPortal;
    private readonly InputAction m_Game_Movement_FireRightPortal;
    private readonly InputAction m_Game_Movement_PauseGame;
    private readonly InputAction m_Game_Movement_Interact;
    public struct Game_MovementActions
    {
        private @PlayerInputActionMaps m_Wrapper;
        public Game_MovementActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Game_Movement_Move;
        public InputAction @Look => m_Wrapper.m_Game_Movement_Look;
        public InputAction @Jump => m_Wrapper.m_Game_Movement_Jump;
        public InputAction @FireLeftPortal => m_Wrapper.m_Game_Movement_FireLeftPortal;
        public InputAction @FireRightPortal => m_Wrapper.m_Game_Movement_FireRightPortal;
        public InputAction @PauseGame => m_Wrapper.m_Game_Movement_PauseGame;
        public InputAction @Interact => m_Wrapper.m_Game_Movement_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Game_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Game_MovementActions set) { return set.Get(); }
        public void AddCallbacks(IGame_MovementActions instance)
        {
            if (instance == null || m_Wrapper.m_Game_MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Game_MovementActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @FireLeftPortal.started += instance.OnFireLeftPortal;
            @FireLeftPortal.performed += instance.OnFireLeftPortal;
            @FireLeftPortal.canceled += instance.OnFireLeftPortal;
            @FireRightPortal.started += instance.OnFireRightPortal;
            @FireRightPortal.performed += instance.OnFireRightPortal;
            @FireRightPortal.canceled += instance.OnFireRightPortal;
            @PauseGame.started += instance.OnPauseGame;
            @PauseGame.performed += instance.OnPauseGame;
            @PauseGame.canceled += instance.OnPauseGame;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IGame_MovementActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @FireLeftPortal.started -= instance.OnFireLeftPortal;
            @FireLeftPortal.performed -= instance.OnFireLeftPortal;
            @FireLeftPortal.canceled -= instance.OnFireLeftPortal;
            @FireRightPortal.started -= instance.OnFireRightPortal;
            @FireRightPortal.performed -= instance.OnFireRightPortal;
            @FireRightPortal.canceled -= instance.OnFireRightPortal;
            @PauseGame.started -= instance.OnPauseGame;
            @PauseGame.performed -= instance.OnPauseGame;
            @PauseGame.canceled -= instance.OnPauseGame;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IGame_MovementActions instance)
        {
            if (m_Wrapper.m_Game_MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGame_MovementActions instance)
        {
            foreach (var item in m_Wrapper.m_Game_MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Game_MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Game_MovementActions @Game_Movement => new Game_MovementActions(this);

    // Game_PauseMenu
    private readonly InputActionMap m_Game_PauseMenu;
    private List<IGame_PauseMenuActions> m_Game_PauseMenuActionsCallbackInterfaces = new List<IGame_PauseMenuActions>();
    private readonly InputAction m_Game_PauseMenu_Pause_MoveUp;
    private readonly InputAction m_Game_PauseMenu_Pause_MoveDown;
    private readonly InputAction m_Game_PauseMenu_Pause_Select;
    private readonly InputAction m_Game_PauseMenu_Pause_Return;
    public struct Game_PauseMenuActions
    {
        private @PlayerInputActionMaps m_Wrapper;
        public Game_PauseMenuActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause_MoveUp => m_Wrapper.m_Game_PauseMenu_Pause_MoveUp;
        public InputAction @Pause_MoveDown => m_Wrapper.m_Game_PauseMenu_Pause_MoveDown;
        public InputAction @Pause_Select => m_Wrapper.m_Game_PauseMenu_Pause_Select;
        public InputAction @Pause_Return => m_Wrapper.m_Game_PauseMenu_Pause_Return;
        public InputActionMap Get() { return m_Wrapper.m_Game_PauseMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Game_PauseMenuActions set) { return set.Get(); }
        public void AddCallbacks(IGame_PauseMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_Game_PauseMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Game_PauseMenuActionsCallbackInterfaces.Add(instance);
            @Pause_MoveUp.started += instance.OnPause_MoveUp;
            @Pause_MoveUp.performed += instance.OnPause_MoveUp;
            @Pause_MoveUp.canceled += instance.OnPause_MoveUp;
            @Pause_MoveDown.started += instance.OnPause_MoveDown;
            @Pause_MoveDown.performed += instance.OnPause_MoveDown;
            @Pause_MoveDown.canceled += instance.OnPause_MoveDown;
            @Pause_Select.started += instance.OnPause_Select;
            @Pause_Select.performed += instance.OnPause_Select;
            @Pause_Select.canceled += instance.OnPause_Select;
            @Pause_Return.started += instance.OnPause_Return;
            @Pause_Return.performed += instance.OnPause_Return;
            @Pause_Return.canceled += instance.OnPause_Return;
        }

        private void UnregisterCallbacks(IGame_PauseMenuActions instance)
        {
            @Pause_MoveUp.started -= instance.OnPause_MoveUp;
            @Pause_MoveUp.performed -= instance.OnPause_MoveUp;
            @Pause_MoveUp.canceled -= instance.OnPause_MoveUp;
            @Pause_MoveDown.started -= instance.OnPause_MoveDown;
            @Pause_MoveDown.performed -= instance.OnPause_MoveDown;
            @Pause_MoveDown.canceled -= instance.OnPause_MoveDown;
            @Pause_Select.started -= instance.OnPause_Select;
            @Pause_Select.performed -= instance.OnPause_Select;
            @Pause_Select.canceled -= instance.OnPause_Select;
            @Pause_Return.started -= instance.OnPause_Return;
            @Pause_Return.performed -= instance.OnPause_Return;
            @Pause_Return.canceled -= instance.OnPause_Return;
        }

        public void RemoveCallbacks(IGame_PauseMenuActions instance)
        {
            if (m_Wrapper.m_Game_PauseMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGame_PauseMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_Game_PauseMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Game_PauseMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Game_PauseMenuActions @Game_PauseMenu => new Game_PauseMenuActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private List<IMainMenuActions> m_MainMenuActionsCallbackInterfaces = new List<IMainMenuActions>();
    private readonly InputAction m_MainMenu_Start_Select_Up;
    private readonly InputAction m_MainMenu_Start_Select_Down;
    private readonly InputAction m_MainMenu_Start_Select;
    public struct MainMenuActions
    {
        private @PlayerInputActionMaps m_Wrapper;
        public MainMenuActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start_Select_Up => m_Wrapper.m_MainMenu_Start_Select_Up;
        public InputAction @Start_Select_Down => m_Wrapper.m_MainMenu_Start_Select_Down;
        public InputAction @Start_Select => m_Wrapper.m_MainMenu_Start_Select;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void AddCallbacks(IMainMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Add(instance);
            @Start_Select_Up.started += instance.OnStart_Select_Up;
            @Start_Select_Up.performed += instance.OnStart_Select_Up;
            @Start_Select_Up.canceled += instance.OnStart_Select_Up;
            @Start_Select_Down.started += instance.OnStart_Select_Down;
            @Start_Select_Down.performed += instance.OnStart_Select_Down;
            @Start_Select_Down.canceled += instance.OnStart_Select_Down;
            @Start_Select.started += instance.OnStart_Select;
            @Start_Select.performed += instance.OnStart_Select;
            @Start_Select.canceled += instance.OnStart_Select;
        }

        private void UnregisterCallbacks(IMainMenuActions instance)
        {
            @Start_Select_Up.started -= instance.OnStart_Select_Up;
            @Start_Select_Up.performed -= instance.OnStart_Select_Up;
            @Start_Select_Up.canceled -= instance.OnStart_Select_Up;
            @Start_Select_Down.started -= instance.OnStart_Select_Down;
            @Start_Select_Down.performed -= instance.OnStart_Select_Down;
            @Start_Select_Down.canceled -= instance.OnStart_Select_Down;
            @Start_Select.started -= instance.OnStart_Select;
            @Start_Select.performed -= instance.OnStart_Select;
            @Start_Select.canceled -= instance.OnStart_Select;
        }

        public void RemoveCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);

    // MainMenu_Settings
    private readonly InputActionMap m_MainMenu_Settings;
    private List<IMainMenu_SettingsActions> m_MainMenu_SettingsActionsCallbackInterfaces = new List<IMainMenu_SettingsActions>();
    private readonly InputAction m_MainMenu_Settings_Settings_Select_Up;
    private readonly InputAction m_MainMenu_Settings_Settings_Select_Down;
    private readonly InputAction m_MainMenu_Settings_Settings_Select;
    public struct MainMenu_SettingsActions
    {
        private @PlayerInputActionMaps m_Wrapper;
        public MainMenu_SettingsActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Settings_Select_Up => m_Wrapper.m_MainMenu_Settings_Settings_Select_Up;
        public InputAction @Settings_Select_Down => m_Wrapper.m_MainMenu_Settings_Settings_Select_Down;
        public InputAction @Settings_Select => m_Wrapper.m_MainMenu_Settings_Settings_Select;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu_Settings; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenu_SettingsActions set) { return set.Get(); }
        public void AddCallbacks(IMainMenu_SettingsActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMenu_SettingsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMenu_SettingsActionsCallbackInterfaces.Add(instance);
            @Settings_Select_Up.started += instance.OnSettings_Select_Up;
            @Settings_Select_Up.performed += instance.OnSettings_Select_Up;
            @Settings_Select_Up.canceled += instance.OnSettings_Select_Up;
            @Settings_Select_Down.started += instance.OnSettings_Select_Down;
            @Settings_Select_Down.performed += instance.OnSettings_Select_Down;
            @Settings_Select_Down.canceled += instance.OnSettings_Select_Down;
            @Settings_Select.started += instance.OnSettings_Select;
            @Settings_Select.performed += instance.OnSettings_Select;
            @Settings_Select.canceled += instance.OnSettings_Select;
        }

        private void UnregisterCallbacks(IMainMenu_SettingsActions instance)
        {
            @Settings_Select_Up.started -= instance.OnSettings_Select_Up;
            @Settings_Select_Up.performed -= instance.OnSettings_Select_Up;
            @Settings_Select_Up.canceled -= instance.OnSettings_Select_Up;
            @Settings_Select_Down.started -= instance.OnSettings_Select_Down;
            @Settings_Select_Down.performed -= instance.OnSettings_Select_Down;
            @Settings_Select_Down.canceled -= instance.OnSettings_Select_Down;
            @Settings_Select.started -= instance.OnSettings_Select;
            @Settings_Select.performed -= instance.OnSettings_Select;
            @Settings_Select.canceled -= instance.OnSettings_Select;
        }

        public void RemoveCallbacks(IMainMenu_SettingsActions instance)
        {
            if (m_Wrapper.m_MainMenu_SettingsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMenu_SettingsActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMenu_SettingsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMenu_SettingsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMenu_SettingsActions @MainMenu_Settings => new MainMenu_SettingsActions(this);

    // MainMenu_SaveSelect
    private readonly InputActionMap m_MainMenu_SaveSelect;
    private List<IMainMenu_SaveSelectActions> m_MainMenu_SaveSelectActionsCallbackInterfaces = new List<IMainMenu_SaveSelectActions>();
    private readonly InputAction m_MainMenu_SaveSelect_Newaction;
    public struct MainMenu_SaveSelectActions
    {
        private @PlayerInputActionMaps m_Wrapper;
        public MainMenu_SaveSelectActions(@PlayerInputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_MainMenu_SaveSelect_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu_SaveSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenu_SaveSelectActions set) { return set.Get(); }
        public void AddCallbacks(IMainMenu_SaveSelectActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMenu_SaveSelectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMenu_SaveSelectActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IMainMenu_SaveSelectActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IMainMenu_SaveSelectActions instance)
        {
            if (m_Wrapper.m_MainMenu_SaveSelectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMenu_SaveSelectActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMenu_SaveSelectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMenu_SaveSelectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMenu_SaveSelectActions @MainMenu_SaveSelect => new MainMenu_SaveSelectActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IGame_MovementActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnFireLeftPortal(InputAction.CallbackContext context);
        void OnFireRightPortal(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IGame_PauseMenuActions
    {
        void OnPause_MoveUp(InputAction.CallbackContext context);
        void OnPause_MoveDown(InputAction.CallbackContext context);
        void OnPause_Select(InputAction.CallbackContext context);
        void OnPause_Return(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnStart_Select_Up(InputAction.CallbackContext context);
        void OnStart_Select_Down(InputAction.CallbackContext context);
        void OnStart_Select(InputAction.CallbackContext context);
    }
    public interface IMainMenu_SettingsActions
    {
        void OnSettings_Select_Up(InputAction.CallbackContext context);
        void OnSettings_Select_Down(InputAction.CallbackContext context);
        void OnSettings_Select(InputAction.CallbackContext context);
    }
    public interface IMainMenu_SaveSelectActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
